### ISSUE TITLE
Add ability to use SSD cache disks, similar to Linux capability

### ISSUE THREAD

**Issue by Napalmsteak** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#4]
I purchased two SSDs after researching ZFS on linux/debian to use as read/write buffers, but cannot find the integration on the OMV version. I know this is an option on the regular desktop versions, is this port capable of utilizing this?

Pulled from open-ZFS page:

"In addition, a dedicated cache device (typically a SSD) can be added to the pool, with zpool add poolname cache devicename. The cache device is managed by the L2ARC, which scans entries that are next to be evicted and writes them to the cache device. The data stored in ARC and L2ARC can be controlled via the primarycache and secondarycache zfs properties respectively, which can be set on both zvols and datasets. Possible settings are all, none and metadata. It is possible to improve performance when a zvol or dataset hosts an application that does its own caching by caching only metadata. One example is PostgreSQL. Another would be a virtual machine using ZFS."

**Comment by nicjo814** [comment]
The plugin is simply a front end to ZFS on Linux, but with some limited capabilities. This means that you can use all features available in ZFS on Linux via the command line if it's missing from the plugin itself. I personally use SSD disks for log/cache so that is definitively possible, but I never came around to implement it in the plugin unfortunately.
Please feel free to close this issue if you're satisfied with the answer.

**Comment by Napalmsteak** [comment]
Thank you! I will close this issue, hopefully i am able to set the SSDs up via command line.
