### ISSUE TITLE
ZFS plugin properties configuration on omv 6

### ISSUE THREAD

**Issue by g2ufo** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#79]
Please add zfs properties configuration of zfs pool as in omv5.
I mean zfs get, zfs set, inherited

**Comment by ryecoaaron** [comment]
I did plan on porting the changes if possible.

**Comment by g2ufo** [comment]
> I did plan on porting the changes if possible. I will remind you that OMV 6 is not even released yet.
ryecoaaron, you did it in the last plugin update. Thanks!

Explain how you implemented the removal of properties, because zfs  has only "zfs get" and "zfs set" command?

**Comment by ryecoaaron** [comment]
I didn't change the backend at all.  I am just re-implementing the frontend.  And I guess the removal doesn't actually work.  It removes it but the property comes back and is changed from default to local.  I will remove the delete function.  This is the problem with someone new to zfs doing the work and not getting any help.

**Comment by ryecoaaron** [comment]
Actually, there is a way to remove a property but it would be difficult to make the plugin do this.  So, I will remove the delete.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/blob/master/usr/share/omvzfs/Dataset.php#L173

Fixed in latest commit.  I will work on a release.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/commit/d249a7606a2699cdccee636215a0b9dd96c6f9b3
