### ISSUE TITLE
Zfs plugin 6.0.12 Connection Lost on installation.

### ISSUE THREAD

**Issue by procount** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#85]
I am trying to setup OMV6 on a Raspberry Pi4 with ZFS and the ZFS plugin, for the third time for my simple home NAS solution.
The first 2 times were successful with earlier versions, but with this latest attempt the ZFS plugin 6.0.12 is failing to install with ***Connection Lost*** message.
My first attempt was with Raspios64-lite OS which had Kernel v5.x. with no issues.
On my second attempt, the Raspios64-lite kernel had updated to v6.1.x and ZFS would not work. I had to use backports to install it as follows:

```
sudo apt install -y git
sudo apt install -y raspberrypi-kernel-headers; # necessary for zfs-dkms to build

#for ZFS on Kernel 6.1
sudo sh -c "echo \"deb http://deb.debian.org/debian bullseye-backports main contrib non-free\" >> /etc/apt/sources.list.d/backports.list"
sudo apt update
sudo apt install -y -t bullseye-backports zfs-dkms #zfs-initramfs
```

On this third attempt with all the latest versions, OMV seems to have been updated. I used the same script above to install ZFS, but when I try to install the ZFS 6.0.12 plugin, I now get the connection lost issue during the installation of the plugin. I have tried several times with the same result. At the moment I have to resort to installing a backup of a previous OMV to get ZFS working.
Does this plugin need upgrading for the latest OMV or Raspios64-lite version?

**Comment by ryecoaaron** [comment]
The connection lost happens when omv-engined is restarted when a plugin (any plugin) is installed.  Nothing I can do to change that but it doesn't stop the install.  Install the plugin from the command line should prove that.  Just hit ctrl-shift-R in the web interface after installing.

I don't think there is anything that needs to be changed in the plugin.  Personally, I would not use zfs on an RPi due to lack of resources and raid on usb (or an RPi) makes no sense. So, I don't test on the RPi.  Since every ARM board is different, I could never test on all of them that OMV runs on anyway.

**Comment by ryecoaaron** [comment]
sudo apt-get install openmediavault-zfs

My RPis are OC'd to 2 or 2.1 as well.  Super stable except for when I was testing zfs on them.  I could never get a multi-TB rsync to finish on an 8GB rpi OC'd or not OC'd with large heatsink and fan (cpu temps always less than 30C).

**Comment by procount** [comment]
Thanks for your insights and experience. 
I had somewhat similar experience on my first drives on zfs. Zfs would disconnect the drives during copying, until I found out they were SMR. Although I haven't tried offsite copying yet, I'm hoping the snapshot ability would be ok using zfs_autobackup. Btrfs is always an option if that fails.

**Comment by ryecoaaron** [comment]
I am using btrfs on one now but not using snapshots since it is a target for borgbackup from my primary server.
